server:
  port: 8080


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  profiles:
    include:
      - basedev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC
  jpa:
    database: mysql
    show-sql: true
  thymeleaf:
    cache: false
